version: '3.9'
services:
    react:
        image: node:14
        ports:
            - 3000:3000
        volumes:
            - ./:/app
        working_dir: /app
        command: npm start
    redis:
        image: redis
        ports:
            - 6379:6379

